### ISSUE TITLE
rm-configs change of VLAN range was not auto updated in model by DTN-RM

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#52]
I added VLAN 1795 to Starlight DTN-1 configs:
https://github.com/sdn-sense/rm-configs/tree/master/T3_US_Starlight_1

After 24 hours, the model still has the old VLAN range "1780,3985-3989".  
@juztas: The DTN server is 165.124.33.142 (dtn110.sl.startap.net).

**Comment by juztas** [comment]
Can I get access to it?

**Comment by juztas** [comment]
https://github.com/sdn-sense/siterm/commit/5c929ccbc2ce77cf09ee3e09b3e9fe1c140f1ffc#diff-405dc3d725624a3b51b863ba25bae2ddR58

It was fixed in new release. It was always using old config to initiate new thread, so never took the new config.  For new release - wait for auto-update fix and then we can update all DTNs.

**Comment by juztas** [comment]
@xi-yang go ahead and update frontend and agents. Be aware - you need to clean all deltas and remove sqlite.db file (under conf/opt/config/<sitename>/sqlite.db
For agent, remove all dir 'conf/opt/config/DTNRM/'
This new release has many new changes - so it needs clean install. In the future we will be able to do without removal, but with simple update.

**Comment by juztas** [comment]
Just tested. New release works and updates vlan range based on configuration

https://github.com/sdn-sense/rm-configs/commit/79000c6aad7539c2f9cb8edaf58f4d0d22ebdee6#diff-6981ac9470e45144a5b33c4bbf9eb7e699fd997c61a0a7194c11caee6f1c69af
